# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - kind/refactoring
  categories:
    - title: "New features"
      labels:
        - kind/feature
    - title: "Packaging"
      labels:
        - kind/packaging
    - title: "Bug fixes"
      labels:
        - kind/fix
    - title: "Dependencies"
      labels:
        - kind/dependencies
      authors:
        - dependabot
    - title: Other Changes
      labels:
        - "*"
