name: build-msi (windows)

on:
  release:
    types:
      - prereleased

jobs:
  build:
    name: Build
    runs-on: windows-2019
    needs: get_latest_release
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - id: set_release_in_env
      run: make -f windows/Makefile.build-version-no-rc >> $env:GITHUB_ENV
    - name: Build
      run: make windows_installer
    - name: Upload MSI
      uses: actions/upload-artifact@v2
      with:
        path: crowdsec*msi
        name: crowdsec.msi
