---
name: Dependency review

on:
  push:
    branches:
      - master
      - releases/**
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
      - releases/**
    paths-ignore:
      - 'README.md'

jobs:
  review:
    name: "Dependency Review"
    runs-on: ubuntu-latest
    steps:
    - name: Check out CrowdSec repository
      uses: actions/checkout@v4
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        deny-licenses: 'MIT'
