name: Publish Docker image on Push to Master

on:
  push:
    branches: [ master ]
    paths:
      - 'pkg/**'
      - 'cmd/**'
      - 'plugins/**'
      - 'docker/docker_start.sh'
      - 'docker/config.yaml'
      - '.github/workflows/publish_docker-image_on_master.yml'
      - 'Dockerfile'
      - 'Dockerfile.debian'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'

jobs:
  dev-alpine:
    uses: ./.github/workflows/publish-docker.yml
    with:
      platform: linux/amd64
      build_version: dev
      latest: false
      push: true
      dockerhub_image: ${{ secrets.DOCKER_USERNAME }}/crowdsec
      ghcr_image: ghcr.io/${{ github.repository_owner }}/crowdsec
      slim: false
      debian: false
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  dev-debian:
    uses: ./.github/workflows/publish-docker.yml
    with:
      platform: linux/amd64
      build_version: dev
      latest: false
      push: true
      dockerhub_image: ${{ secrets.DOCKER_USERNAME }}/crowdsec
      ghcr_image: ghcr.io/${{ github.repository_owner }}/crowdsec
      slim: false
      debian: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
